# Build settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Site settings
title: Software Freedom Day 2014
email: info@nosk.org.np
description: "Software Freedom Day is celebrated all around the Globe"
baseurl: ""
url: "http://openosk.github.io/"
permalink: /blog/:title
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""

# Location block
eventLocationName: "NCIT College Premises"
eventLocationAddress: "Balkumari, Lalitpur, Nepal"
eventStartTime: "2014-10-18T10:00"
eventStartTimeHumanReadable: "10:00"
eventEndTime: "2014-10-18T20:00"
eventEndTimeHumanReadable: "20:00"
eventPlaceCoordinates: "27.671387, 85.338811"
mapCenterCoordinates: "27.671387, 85.338811"
mapMobileCenterCoordinates: "27.671387, 85.338811"

# Logistics Location Block
logisticsMapCenterCoordinates: "27.671387, 85.338811"
logisticsMapMobileCenterCoordinates: "27.671387, 85.338811"

#Tweets feed
twitterHashTag: "sfdNosk14"
twitterFeed: "http://twitter.com/open_nosk"

# Subscribe
subscribeAction: ""

# Documents
#c4pUrl: "http://bit.ly/dfua-c4p"
#c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"

# Head
metaKeywords: "event, sfd, nosk, opensource, sfd2014"
twitterAccount: "@open_nosk"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Header
eventDate: "September 20, 2014"
typeoutTextValues: '"", "Presentation", "Talks", "Destro Demo", "Software Demo", "Open Art", "Gaming"'

# About Event Block
eventName: "Software Freedom Day"

# Team Block
aboutUs: NOSK stands for Nepal Open Source Klub. It was established in 28th Feb 2008 by the FOSS enthusiastic students from NCIT (Nepal College of Information Technology), Balkumari, Lalitpur, Nepal.

# Speakers List Block
showSessions: true
thumbnailsFolder: /img/speakers/

# Footer
gplusFollowUsUrl: "https://plus.google.com/communities/110589297196280370630"
twitterFollowUsUrl: "https://twitter.com/intent/user?screen_name=open_nosk"
fbFollowUsUrl: "https://facebook.com/nosklub"

# Blog
blogCommentsEnabled: true
discusShortName: "openosk"
